# Generated by Django 2.2.3 on 2019-08-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190411_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
